// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var SjclComplete = require("sjcl-complete");

console.log(0);

Zora.test("Bignum toString test", (function (t) {
        console.log(1);
        var n1 = new SjclComplete.bn(12312434);
        console.log(2);
        var n2 = n1.power(10);
        var str = n2.toString();
        t.equal(str, "0xb99c06973dcc72429aa1dd41b0bc40a424289a05d3d72f066ee4e71c400", "Should match");
        console.log(str);
        console.log(2);
      }));

/*  Not a pure module */
