// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SjclComplete = require("sjcl-complete");

var Bn = {};

var a = new SjclComplete.bn("10");

exports.Bn = Bn;
exports.a = a;
/* a Not a pure module */
